# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
    config.vm.define :emberStart do |a_config|
        a_config.vm.box = "ubuntu12.10"
        a_config.vm.box_url = "http://static.aldoborrero.com/vagrant/quantal64.box"
        a_config.vm.host_name = "ember-starterkit-vm"
        #a_config.vm.customize ["modifyvm", :id, "--memory", 512]
        a_config.vm.network :hostonly, "172.22.22.23"
        a_config.vm.share_folder "vagrant-root", "/vagrant", "../" #, :nfs => true
        #a_config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
        a_config.vm.forward_port 80, 8080 #apache2

        a_config.vm.provision :chef_solo do |chef|
            chef.cookbooks_path = ["cookbooks", "custom_cookbooks"]

            chef.add_recipe "build-essential"
            chef.add_recipe "apt"
            chef.add_recipe "openssl"
            chef.add_recipe "apache2"
            chef.add_recipe "git"
            chef.add_recipe "apache2::mod_rewrite"
            chef.add_recipe "apache2::mod_deflate"
            chef.add_recipe "apache2::mod_headers"
            chef.add_recipe "apache2_vhosts"

            #mount point always uses 'vagrant' as a user
            chef.add_recipe "apache2_runAsUser"

            chef.json = {
                :apache2 => {
                    :keepaliverequests => 100,
                    :keepalivetimeout => 5,
                    :listen_ports => ["80", "443"]
                }
            }
        end

        a_config.vm.provision :shell,
            :inline => "echo \"127.0.0.1     deployment.dev\" >> /etc/hosts"
    end
end
